# Generated by Django 3.2.6 on 2022-11-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'accepted'), ('Completed', 'Completed'), ('Cenceled', 'Cenceled')], default='New', max_length=10),
        ),
    ]
