# Generated by Django 3.2.6 on 2022-11-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20221118_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cenceled', 'Cenceled'), ('Completed', 'Completed'), ('Accepted', 'accepted'), ('New', 'New')], default='New', max_length=10),
        ),
    ]
