# Generated by Django 3.2.6 on 2022-11-20 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0006_auto_20221118_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Accepted', 'accepted'), ('Cenceled', 'Cenceled')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderrree', to=settings.AUTH_USER_MODEL),
        ),
    ]
