# Generated by Django 3.2.6 on 2022-11-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20221120_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'accepted'), ('Completed', 'Completed'), ('Cenceled', 'Cenceled')], default='New', max_length=10),
        ),
    ]
