# Generated by Django 3.2.6 on 2022-11-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_createservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='createservice',
            name='your_sertificate',
            field=models.ImageField(default=4, upload_to='photos/competence'),
            preserve_default=False,
        ),
    ]
