# Generated by Django 3.2.6 on 2022-11-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_createservice_your_sertificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createservice',
            name='wilaya',
        ),
    ]
