# Generated by Django 3.2.6 on 2022-11-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_createservice_your_sertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createservice',
            name='your_sertificate',
            field=models.FileField(upload_to=''),
        ),
    ]
