# Generated by Django 3.2.6 on 2022-11-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_createservice_your_sertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createservice',
            name='your_sertificate',
            field=models.ImageField(upload_to='photos/Competence'),
        ),
    ]
