# Generated by Django 3.2.6 on 2022-11-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_remove_createservice_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createservice',
            old_name='owner',
            new_name='user',
        ),
    ]
