# Generated by Django 3.2.6 on 2022-11-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_rename_owner_createservice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='createservice',
            name='images',
            field=models.ImageField(default=5, upload_to='photos/Ser'),
            preserve_default=False,
        ),
    ]
